# Generated by Django 4.1.3 on 2022-11-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdata",
            name="predicted_items",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
