# Generated by Django 4.1.3 on 2022-11-22 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_userdata_predicted_items"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userdata",
            old_name="souldgoodno",
            new_name="soulgoodno",
        ),
    ]
