# Generated by Django 4.1.3 on 2022-11-22 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_souldgoodno_userdata_soulgoodno"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userdata",
            name="predicted_items",
        ),
    ]
